name: Publish

on:
  push:
    tags: ["v*.*.*"]

env:
  OTP_VERSION_SPEC: "25.3"
  ELIXIR_VERSION_SPEC: "1.13.4"

jobs:
  test:
    uses: ./.github/workflows/test.yml
  publish:
    needs: test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.OTP_VERSION_SPEC }}
          elixir-version: ${{ env.ELIXIR_VERSION_SPEC }}

      # https://hex.pm/docs/publish
      - name: Publish
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
        run: |
          mix deps.get
          mix hex.publish --yes
